Music/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.Models
{

    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }
}

Music/ViewModels/ChangePasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.ViewModels
{
    public class ChangePasswordViewModel
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string NewPassword { get; set; }
    }
}

Music/ViewModels/EditUserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.ViewModels
{
    public class EditUserViewModel
    {
        public string Id { get; set; }
        public string Email { get; set; }
    }
}

Music/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Music.Models;
using Music.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Music.Controllers
{
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<IdentityUser> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Music/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Music.Models;
using Microsoft.AspNetCore.Identity;

namespace HelloWebApi.Controllers
{
    [Route("api/[controller]")]
    public class UserController : Controller
    {
        ApplicationDbContext _context;
        public UserController(ApplicationDbContext context)
        {
            this._context = context;
           
        }

        [HttpGet]
        public IEnumerable<IdentityUser> Get()
        {
            return _context.Users.ToList();
        }

        // GET api/users/5
        [HttpGet("{id}")]
        public IActionResult Get(string id)
        {
            IdentityUser user = _context.Users.FirstOrDefault(x => x.Id == id);
            if (user == null)
                return NotFound();
            return new ObjectResult(user);
        }

        // POST api/users
        [HttpPost]
        public IActionResult Post([FromBody]IdentityUser user)
        {
            if (user == null)
            {
                return BadRequest();
            }

            _context.Users.Add(user);
            _context.SaveChanges();
            return Ok(user);
        }

        // PUT api/users/
        [HttpPut]
        public IActionResult Put([FromBody]IdentityUser user)
        {
            if (user == null)
            {
                return BadRequest();
            }
            if (!_context.Users.Any(x => x.Id == user.Id))
            {
                return NotFound();
            }

            _context.Update(user);
            _context.SaveChanges();
            return Ok(user);
        }

        // DELETE api/users/5
        [HttpDelete("{id}")]
        public IActionResult Delete(string id)
        {
            IdentityUser user = _context.Users.FirstOrDefault(x => x.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            _context.Users.Remove(user);
            _context.SaveChanges();
            return Ok(user);
        }
    }
}

Music/Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Music.Models;
using Music.ViewModels;

namespace Music.Controllers
{
    public class UsersController : Controller
    {
        UserManager<IdentityUser> _userManager;

        public UsersController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());
        
        public IActionResult EditUsers() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = new IdentityUser { Email = model.Email, UserName = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            IdentityUser user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;


                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            IdentityUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ChangePassword(string id)
        {
            IdentityUser user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    var _passwordValidator =
                        HttpContext.RequestServices.GetService(typeof(IPasswordValidator<IdentityUser>)) as IPasswordValidator<IdentityUser>;
                    var _passwordHasher =
                        HttpContext.RequestServices.GetService(typeof(IPasswordHasher<IdentityUser>)) as IPasswordHasher<IdentityUser>;

                    IdentityResult result =
                        await _passwordValidator.ValidateAsync(_userManager, user, model.NewPassword);
                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.NewPassword);
                        await _userManager.UpdateAsync(user);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }

        public IActionResult DeleteUser()
        {
            return View();
        }
    }
}

Music/Views/Users/ChangePassword.cshtml
@model Music.ViewModels.ChangePasswordViewModel
@{
    ViewBag.Title = "Изменение пароля";
}
<h2>Изменение пароля для пользователя @Model.Email</h2>
<form asp-action="ChangePassword" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="Email" />

    <div class="form-group">
        <label asp-for="NewPassword" class="control-label">@SharedLocalizer["Password"]</label>
        <input type="text" asp-for="NewPassword" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value=@SharedLocalizer["Save"] class="btn btn-default" />
    </div>
</form>

Music/Views/Users/Create.cshtml
@model Music.ViewModels.CreateUserViewModel
@{
    ViewBag.Title = "Добавление пользователя";
}
<form asp-action="Create" asp-controller="Users" method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label">Email</label>
        <div class="col-md-5">
            <input type="text" asp-for="Email" class="form-control" />
            <span asp-validation-for=Email class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label">@SharedLocalizer["Password"]</label>
        <div class="col-md-5">
            <input type="text" asp-for="Password" class="form-control" />
            <span asp-validation-for=Password class="text-danger"></span>
        </div>
    </div>
   
    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" value=@SharedLocalizer["Add"] class="btn btn-info" />
        </div>
    </div>
</form>

Music/Views/Users/DeleteUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Список пользователей</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
</head>
<body>
    <h2>Список пользователей</h2>

    <table class="table table-condensed table-striped table-bordered">
        <thead><tr><th>Id</th><th>Email</th><th></th></tr></thead>
        <tbody></tbody>
    </table>

    <script>
        // Получение всех пользователей
        function GetUsers() {
            $.ajax({
                url: '/api/user',
                type: 'GET',
                contentType: "application/json",
                success: function (users) {
                    var rows = "";
                    $.each(users, function (index, user) {
                        // добавляем полученные элементы в таблицу
                        rows += row(user);
                    })
                    $("table tbody").append(rows);
                 }
            });
        }
        // Получение одного пользователя
        function GetUser(id) {
            $.ajax({
                url: '/api/user/'+id,
                type: 'GET',
                contentType: "application/json",
                success: function (user) {
                    var form = document.forms["userForm"];
                    form.elements["id"].value = user.id;
                    form.elements["Email"].value = user.Email;
                    form.elements["Password"]

                }
            });
        }

        // Удаление пользователя
        function DeleteUser(id) {
            $.ajax({
                url: "api/user/"+id,
                contentType: "application/json",
                method: "DELETE",
                success: function (user) {
                    $("tr[data-rowid='" + user.id + "']").remove();
                }
            })
        }
        // создание строки для таблицы
        var row = function (user) {
            return "<tr data-rowid='" + user.id + "'><td>" + user.id + "</td>" +
                "<td>" + user.email + "</td>" +
                   "<td><a class='removeLink' data-id='" + user.id + "'>Удалить</a></td></tr>";
        }
        // сброс значений формы
        $("#reset").click(function (e) {

            e.preventDefault();
            reset();
        })


        // нажимаем на ссылку Удалить
        $("body").on("click", ".removeLink", function () {
            var id = $(this).data("id");
            DeleteUser(id);
        })

        // загрузка пользователей
        GetUsers();

    </script>
</body>
</html>

Music/Views/Users/Edit.cshtml
@model Music.ViewModels.EditUserViewModel
@{
    ViewBag.Title = "Редактирование пользователя";
}
<head>
    <link rel="stylesheet" type="text/css" href="~/css/default.css" />
    <link rel="stylesheet" type="text/css" href="~/css/component.css" />
    <link rel="stylesheet" type="text/css" href="~/css/dropdown.css" />
    <link rel="stylesheet" type="text/css" href="~/css/search.css" />
    <link rel="stylesheet" type="text/css" href="~/css/btn.css" />
</head>
<form asp-action="Edit" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <div class="col-md-5">
            <input type="text" asp-for="Email" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <input type="submit" value=@SharedLocalizer["Save"] class="btn btn-default" />
    </div>
</form>

Music/Views/Users/EditUsers.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityUser>
@{
    ViewBag.Title = "Изменение пользователей";
}

<table class="table">
    <tr><th>Email</th><th></th></tr>
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Email</td>

            <td>
                <form asp-action="Delete" asp-route-id="@user.Id" method="post">
                    <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@user.Id">@SharedLocalizer["Edit"]</a>
                    <a class="btn btn-sm btn-primary" asp-action="ChangePassword" asp-route-id="@user.Id">@SharedLocalizer["Change password"]</a>
                    <a class="btn btn-sm btn-primary" asp-controller="Roles" asp-action="Edit" asp-route-userid="@user.Id">@SharedLocalizer["Access rights"]</a>
                </form>
            </td>
        </tr>
    }
</table>

Music/Views/Users/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityUser>
@{
    ViewBag.Title = "Список пользователей";
}

<body>
    <style>
        .list-group{
            padding: 70px;
        }
        .list-group-item {
            background-color: #121212;
            color: white;
        }
    </style>
    <div class="list-group">
        <h2>@SharedLocalizer["Edit users"]</h2>
        <a class="list-group-item" asp-action="Create">@SharedLocalizer["Add user"]</a>
        @*<a class="list-group-item" href="~/index.html">@SharedLocalizer["Delete user"]</a>*@
        <a class="list-group-item" asp-controller="Users"  asp-action="DeleteUser">@SharedLocalizer["Delete user"]</a>
        <a class="list-group-item" asp-action="EditUsers">@SharedLocalizer["Edit user"]</a>
        <a class="list-group-item" asp-controller="Roles" asp-action="Create">@SharedLocalizer["Add role"]</a>
        <a class="list-group-item" asp-controller="Roles" asp-action="Index">@SharedLocalizer["List roles"]</a>
    </div>
</body>