Music/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.Models
{

    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }
}

Music/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Music.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Music.Controllers
{
    public class AlbumController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _environment;


        public AlbumController(ApplicationDbContext context, IHostingEnvironment IHostingEnvironment)
        {
            _context = context;
            _environment = IHostingEnvironment;
        }

        public IActionResult Create()
        {
            ViewBag.Genres = new SelectList(_context.Genres, "Id", "Name");
            ViewBag.Artists = new SelectList(_context.Artists, "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(string name, Album album)
        {
            var newFileName = string.Empty;

            if (HttpContext.Request.Form.Files != null)
            {
                var fileName = string.Empty;
                string PathDB = string.Empty;

                var files = HttpContext.Request.Form.Files;

                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        //Getting FileName
                        fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                        //Assigning Unique Filename (Guid)
                        var myUniqueFileName = Convert.ToString(Guid.NewGuid());

                        //Getting file Extension
                        var FileExtension = Path.GetExtension(fileName);

                        // concating  FileName + FileExtension
                        newFileName = myUniqueFileName + FileExtension;

                        // Combines two strings into a path.
                        fileName = Path.Combine(_environment.WebRootPath, "demoImages") + $@"\{newFileName}";

                        // if you want to store path of folder in database
                        PathDB = "demoImages/" + newFileName;

                        using (FileStream fs = System.IO.File.Create(fileName))
                        {
                            file.CopyTo(fs);
                            fs.Flush();
                        }
                    }
                }


            }

            if (ModelState.IsValid)
            {
                album.AlbumArtUrl = newFileName;
                _context.Albums.Add(album);
                _context.SaveChanges();

                return RedirectToAction("Index", "Manager");
            }
            return View(album);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Artist artist = await _context.Artists.FirstOrDefaultAsync(p => p.Id == id);
                if (artist != null)
                    return View(artist);
            }
            return NotFound();


        }
        [HttpPost]
        public async Task<IActionResult> Edit(Album album)
        {
            _context.Update(album);
            //_context.Entry(artist).State = EntityState.Modified;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Manager");


        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Album album = await _context.Albums.FirstOrDefaultAsync(p => p.Id == id);
                if (album != null)
                    return View(album);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {

            if (id != null)
            {
                Album album = new Album { Id = id.Value };
                _context.Entry(album).State = EntityState.Deleted;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Manager");
            }
            return NotFound();
        }   

        public IActionResult GetEmpList()
        {
            var albums = _context.Albums.ToList();
            return View(albums);
        }

    }
}

Music/Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Music.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Music.Controllers
{
    public class ArtistController : Controller
    {
        private readonly ApplicationDbContext _context;
        
        public ArtistController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Artist artist)
        {
            if (ModelState.IsValid)
            {
                _context.Artists.Add(artist);
                _context.SaveChanges();
                return RedirectToAction("Index", "Manager");
            }
            return View(artist);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Artist artist = await _context.Artists.FirstOrDefaultAsync(p => p.Id == id);
                if(artist != null)
                    return View(artist);
            }
            return NotFound();
            
            
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Artist artist)
        {   
            _context.Update(artist);
            //_context.Entry(artist).State = EntityState.Modified;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Manager");
           
            
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Artist artist = await _context.Artists.FirstOrDefaultAsync(p => p.Id == id);
                if (artist != null)
                    return View(artist);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            
            if (id != null)
            {
                Artist artist = new Artist { Id = id.Value };
                _context.Entry(artist).State = EntityState.Deleted;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Manager");
            }
            return NotFound();
        }

    }
}

Music/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Music.Models;
using Microsoft.EntityFrameworkCore;
using Music.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Net.Http.Headers;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Music.Controllers
{
    public class ManagerController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _environment;

        
        public ManagerController(ApplicationDbContext context, IHostingEnvironment IHostingEnvironment)
        {
            _context = context;
            _environment = IHostingEnvironment;
        }
        
        public IActionResult Index()
        {
            
            ViewBag.Artists = _context.Artists;
            ViewBag.Genres = _context.Genres;
            ViewBag.Albums = _context.Albums;
            ViewBag.Songs = _context.Songs;
            return View();
        }

        //public IActionResult AddArtist()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public IActionResult AddArtist(Artist artist)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Artists.Add(artist);
        //        _context.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(artist);
        //}

        //public IActionResult AddAlbum()
        //{
        //    ViewBag.Genres = new SelectList(_context.Genres, "Id", "Name");
        //    ViewBag.Artists = new SelectList(_context.Artists, "Id", "Name");
        //    return View();
        //}

        //[HttpPost]
        //public IActionResult AddAlbum(string name, Album album)
        //{
        //    var newFileName = string.Empty;

        //    if (HttpContext.Request.Form.Files != null)
        //    {
        //        var fileName = string.Empty;
        //        string PathDB = string.Empty;

        //        var files = HttpContext.Request.Form.Files;

        //        foreach (var file in files)
        //        {
        //            if (file.Length > 0)
        //            {
        //                //Getting FileName
        //                fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

        //                //Assigning Unique Filename (Guid)
        //                var myUniqueFileName = Convert.ToString(Guid.NewGuid());

        //                //Getting file Extension
        //                var FileExtension = Path.GetExtension(fileName);

        //                // concating  FileName + FileExtension
        //                newFileName = myUniqueFileName + FileExtension;

        //                // Combines two strings into a path.
        //                fileName = Path.Combine(_environment.WebRootPath, "demoImages") + $@"\{newFileName}";

        //                // if you want to store path of folder in database
        //                PathDB = "demoImages/" + newFileName;

        //                using (FileStream fs = System.IO.File.Create(fileName))
        //                {
        //                    file.CopyTo(fs);
        //                    fs.Flush();
        //                }
        //            }
        //        }


        //    }

        //    if (ModelState.IsValid)
        //    {
        //        album.AlbumArtUrl = newFileName;
        //        _context.Albums.Add(album);
        //        _context.SaveChanges();

        //        return RedirectToAction("Index");
        //    }
        //    return View(album);
        //}

        //public IActionResult AddSong()
        //{
        //    ViewBag.Albums = new SelectList(_context.Albums, "Id", "Title");
        //    return View();
        //}

        //[HttpPost]
        //public IActionResult AddSong(Song song)
        //{
            
            
        //    if (ModelState.IsValid)
        //    {
                
        //        _context.Songs.Add(song);
        //        _context.SaveChanges();

        //        return RedirectToAction("Index");
        //    }
        //    return View(song);
        //}
    }
}

Music/Controllers/SongController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Music.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Music.Controllers
{
    public class SongController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _environment;

        public SongController(ApplicationDbContext context, IHostingEnvironment IHostingEnvironment)
        {
            _context = context;
            _environment = IHostingEnvironment;
        }

        public IActionResult Create()
        {
            ViewBag.Albums = new SelectList(_context.Albums, "Id", "Title");
            return View();
        }

        [HttpPost]
        public IActionResult Create(string name, Song song)
        {
            var newFileName = string.Empty;

            if (HttpContext.Request.Form.Files != null)
            {
                var fileName = string.Empty;
                string PathDB = string.Empty;

                var files = HttpContext.Request.Form.Files;

                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        //Getting FileName
                        fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                        //Assigning Unique Filename (Guid)
                        var myUniqueFileName = Convert.ToString(Guid.NewGuid());

                        //Getting file Extension
                        var FileExtension = Path.GetExtension(fileName);

                        // concating  FileName + FileExtension
                        newFileName = myUniqueFileName + FileExtension;

                        // Combines two strings into a path.
                        fileName = Path.Combine(_environment.WebRootPath, "audio") + $@"\{newFileName}";

                        // if you want to store path of folder in database
                        PathDB = "audio/" + newFileName;

                        using (FileStream fs = System.IO.File.Create(fileName))
                        {
                            file.CopyTo(fs);
                            fs.Flush();
                        }
                    }
                }


            }
            if (ModelState.IsValid)
            {
                song.AudiotUrl = newFileName;
                _context.Songs.Add(song);
                _context.SaveChanges();

                return RedirectToAction("Index", "Manager");
            }
            return View(song);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Artist artist = await _context.Artists.FirstOrDefaultAsync(p => p.Id == id);
                if (artist != null)
                    return View(artist);
            }
            return NotFound();


        }
        [HttpPost]
        public async Task<IActionResult> Edit(Song song)
        {
            _context.Update(song);
            //_context.Entry(artist).State = EntityState.Modified;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Manager");


        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Song song = await _context.Songs.FirstOrDefaultAsync(p => p.Id == id);
                if (song != null)
                    return View(song);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {

            if (id != null)
            {
                Song song = new Song { Id = id.Value };
                _context.Entry(song).State = EntityState.Deleted;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Manager");
            }
            return NotFound();
        }
    }
}

Music/Views/Manager/AddAlbum.cshtml
@model Album
@{
    ViewBag.Title = "AddAlbum";
}

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

<form asp-action="AddAlbum" method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for=Title class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for=Title class="form-control" />
            <span asp-validation-for=Title class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for=Price class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for=Price class="form-control" />
            <span asp-validation-for=Price class="text-danger"></span>
        </div>
    </div>


    @*<div class="form-group">
            <label asp-for=AlbumArtUrl class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for=AlbumArtUrl class="form-control" />
                <span asp-validation-for=AlbumArtUrl class="text-danger"></span>
            </div>
        </div>*@


    <div class="form-group">
        <div class="col-md-5">
            <p>Upload one or more files using this form:</p>
            <input asp-for=AlbumArtUrl type="file" name="files" multiple />
        </div>
    </div>
        @*<div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Upload" />
            </div>
        </div>*@



    <div class="form-group">
        <label asp-for=ArtistId class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <select asp-for=ArtistId class="form-control" asp-items=@ViewBag.Artists>
                @*<option selected="selected" disabled="disabled">Select Artist</option>*@
            </select>
        </div>
    </div>

    <div class="form-group">
        <label asp-for=GenreId class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <select asp-for=GenreId class="form-control" asp-items=@ViewBag.Genres>
                @*<option selected="selected" disabled="disabled">Select Genre</option>*@
            </select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-info" value="Upload" />
        </div>
    </div>
</form>

Music/Views/Manager/AddArtist.cshtml
@model Artist

<form asp-action="AddArtist" method="post" class="form-horizontal" role="form">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for=Name class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for=Name class="form-control" />
            <span asp-validation-for=Name class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-info" value="Add new artist" />
        </div>
    </div>
</form>

Music/Views/Manager/AddSong.cshtml
@model Song
@{
    ViewBag.Title = "AddSong";
}

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

<form asp-action="AddSong" method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for=Name class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for=Name class="form-control" />
            <span asp-validation-for=Name class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for=AlbumId class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <select asp-for=AlbumId class="form-control" asp-items=@ViewBag.Albums>
                @*<option selected="selected" disabled="disabled">Select Artist</option>*@
            </select>
        </div>
    </div>

    
    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-info" value="Upload" />
        </div>
    </div>
</form>

Music/Views/Manager/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/css/default.css" />
    <link rel="stylesheet" type="text/css" href="~/css/component.css" />
    <link rel="stylesheet" type="text/css" href="~/css/dropdown.css" />
    <link rel="stylesheet" type="text/css" href="~/css/search.css" />
    <link rel="stylesheet" type="text/css" href="~/css/btn.css" />
    <script src="~/js/panel.js"></script>
</head>
<body>
    <div class="container">
        <style>
            .row{
                color:black;
            }

        </style>
        <div class="row">
            <div class="col-md-6">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
                        <h3 class="panel-title">
                            <a asp-controller="Artist" asp-action="Create" class="btn btn-info">@SharedLocalizer["Add artist"]</a>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <ul class="list-group">
                            @foreach (var artist in ViewBag.Artists)
                            {
                            <li class="list-group-item">
                                @artist.Name
                                
                                <a asp-controller="Artist" asp-action="Edit" asp-route-id="@artist.Id"> Edit | </a>
                                <a asp-controller="Artist" asp-action="Delete" asp-route-id="@artist.Id">Delete</a>
                            </li>
                                
                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
                        <h3 class="panel-title">
                            <a asp-controller="Album" asp-action="Create" class="btn btn-info">@SharedLocalizer["Add album"]</a>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <ul class="list-group">
                            @foreach (var album in ViewBag.Albums)
                            {
                            <li class="list-group-item">
                                @album.Title
                                <a asp-controller="Album" asp-action="Edit" asp-route-id="@album.Id"> Edit | </a>
                                <a asp-controller="Album" asp-action="Delete" asp-route-id="@album.Id">Delete</a>
                            </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
                        <h3 class="panel-title">
                            <a asp-controller="Song" asp-action="Create" class="btn btn-info">@SharedLocalizer["Add song"]</a>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <ul class="list-group">
                            @foreach (var song in ViewBag.Songs)
                            {
                            <li class="list-group-item">
                                @song.Name
                                <a asp-controller="Song" asp-action="Edit" asp-route-id="@song.Id"> Edit | </a>
                                <a asp-controller="Song" asp-action="Delete" asp-route-id="@song.Id">Delete</a>
                            </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

Music/Views/Manager/Users.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Список пользователей</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
</head>
<body>
    <h2>Список пользователей</h2>
    <form name="userForm">
        <input type="hidden" name="id" value="0" />
        <div class="form-group">
            <label for="name">Имя:</label>
            <input class="form-control" name="name" />
        </div>
        <div class="form-group">
            <label for="age">Возраст:</label>
            <input class="form-control" name="age" />
        </div>
        <div class="panel-body">
            <button type="submit" class="btn btn-sm btn-primary">Сохранить</button>
            <a id="reset" class="btn btn-sm btn-primary">Сбросить</a>
        </div>
    </form>
    <table class="table table-condensed table-striped table-bordered">
        <thead><tr><th>Id</th><th>Имя</th><th>возраст</th><th></th></tr></thead>
        <tbody></tbody>
    </table>

    <script>
        // Получение всех пользователей
        function GetUsers() {
            $.ajax({
                url: '/api/users',
                type: 'GET',
                contentType: "application/json",
                success: function (users) {
                    var rows = "";
                    $.each(users, function (index, user) {
                        // добавляем полученные элементы в таблицу
                        rows += row(user);
                    })
                    $("table tbody").append(rows);
                 }
            });
        }
        // Получение одного пользователя
        function GetUser(id) {
            $.ajax({
                url: '/api/users/'+id,
                type: 'GET',
                contentType: "application/json",
                success: function (user) {
                    var form = document.forms["userForm"];
                    form.elements["id"].value = user.id;
                    form.elements["name"].value = user.name;
                    form.elements["age"].value = user.age;
                }
            });
        }
        // Добавление пользователя
        function CreateUser(userName, userAge) {
            $.ajax({
                url: "api/users",
                contentType: "application/json",
                method: "POST",
                data: JSON.stringify({
                    name: userName,
                    age: userAge
                }),
                success: function (user) {
                    reset();
                    $("table tbody").append(row(user));
                }
            })
        }
        // Изменение пользователя
        function EditUser(userId, userName, userAge) {
            $.ajax({
                url: "api/users",
                contentType: "application/json",
                method: "PUT",
                data: JSON.stringify({
                    id: userId,
                    name: userName,
                    age: userAge
                }),
                success: function (user) {
                    reset();
                    $("tr[data-rowid='" + user.id + "']").replaceWith(row(user));
                }
            })
        }

        // сброс формы
        function reset() {
            var form = document.forms["userForm"];
            form.reset();
            form.elements["id"].value = 0;
        }

        // Удаление пользователя
        function DeleteUser(id) {
            $.ajax({
                url: "api/users/"+id,
                contentType: "application/json",
                method: "DELETE",
                success: function (user) {
                    $("tr[data-rowid='" + user.id + "']").remove();
                }
            })
        }
        // создание строки для таблицы
        var row = function (user) {
            return "<tr data-rowid='" + user.id + "'><td>" + user.id + "</td>" +
                   "<td>" + user.name + "</td> <td>" + user.age + "</td>" +
                   "<td><a class='editLink' data-id='" + user.id + "'>Изменить</a> | " +
                    "<a class='removeLink' data-id='" + user.id + "'>Удалить</a></td></tr>";
        }
        // сброс значений формы
        $("#reset").click(function (e) {

            e.preventDefault();
            reset();
        })

        // отправка формы
        $("form").submit(function (e) {
            e.preventDefault();
            var id = this.elements["id"].value;
            var name = this.elements["name"].value;
            var age = this.elements["age"].value;
            if (id == 0)
                CreateUser(name, age);
            else
                EditUser(id, name, age);
        });

        // нажимаем на ссылку Изменить
        $("body").on("click", ".editLink", function () {
            var id = $(this).data("id");
            GetUser(id);
        })
        // нажимаем на ссылку Удалить
        $("body").on("click", ".removeLink", function () {
            var id = $(this).data("id");
            DeleteUser(id);
        })

        // загрузка пользователей
        GetUsers();

    </script>
</body>
</html>